server:
  port: 8089

spring:
  application:
    name: mybatis-plus-001
  #配置数据源，注意dataSource的缩进问题，不要缩进太多，仅次于spring即可
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource       # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver           # mysql驱动包
    url: jdbc:mysql://localhost:3306/mybatis-plus?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456